name: pystock-data-features
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - mlflow
    - scikit-learn
    - great-expectations==0.13.15
    - pandas-profiling
    - xgboost