
services:
  dev_env:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./:/home/jovyan/

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - "host:container"
      - 5000:5000
    volumes:
      - mlflow_data:/mlruns
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]


volumes:
  mlflow_data:
    driver: local
    labels:
      purpose: "mlflow model tracking data"


