channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.3
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==1.24.4
  - psutil==5.9.5
  - scikit-learn==1.3.1
  - scipy==1.11.3
  - requests==2.31.0
  - mlflow>=1.18.0
  - pandas
  - cloudpickle
  - pandas_datareader==0.10.0
  - yfinance
name: mlflow-env