name: pystock-data-features
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23
  - scipy
  - pandas
  - cloudpickle
  - yfinance=0.2.28
  - pip:
    - mlflow
    - pandas_datareader
    - great-expectations==0.18.19
    - pandas-profiling